// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/terasurfer/Cartelize-Server/accounts/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateCustomerHandler(m, endpoints, options["CreateCustomer"])
	makeCreateAdminHandler(m, endpoints, options["CreateAdmin"])
	makeGetCustomerByIDHandler(m, endpoints, options["GetCustomerByID"])
	makeGetCustomerByEmailHandler(m, endpoints, options["GetCustomerByEmail"])
	makeGetAdminByIDHandler(m, endpoints, options["GetAdminByID"])
	makeGetAdminByEmailHandler(m, endpoints, options["GetAdminByEmail"])
	makeUpdateCustomerHandler(m, endpoints, options["UpdateCustomer"])
	makeUpdateAdminHandler(m, endpoints, options["UpdateAdmin"])
	return m
}
