// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/terasurfer/Cartelize-Server/db/pkg/endpoint"
	pb "github.com/terasurfer/Cartelize-Server/db/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	connectDB grpc.Handler
	getDB     grpc.Handler
	init      grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.DbServer {
	return &grpcServer{
		connectDB: makeConnectDBHandler(endpoints, options["ConnectDB"]),
		getDB:     makeGetDBHandler(endpoints, options["GetDB"]),
		init:      makeInitHandler(endpoints, options["Init"]),
	}
}
