// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
	endpoint "github.com/terasurfer/Cartelize-Server/db/pkg/endpoint"
	service "github.com/terasurfer/Cartelize-Server/db/pkg/service"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initGRPCHandler(endpoints, g)
	return g
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"ConnectDB": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "ConnectDB", logger))},
		"GetDB":     {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GetDB", logger))},
		"Init":      {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "Init", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["ConnectDB"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ConnectDB")), endpoint.InstrumentingMiddleware(duration.With("method", "ConnectDB"))}
	mw["GetDB"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetDB")), endpoint.InstrumentingMiddleware(duration.With("method", "GetDB"))}
	mw["Init"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "Init")), endpoint.InstrumentingMiddleware(duration.With("method", "Init"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"ConnectDB", "GetDB", "Init"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
