// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
	endpoint "github.com/terasurfer/Cartelize-Server/accounts/pkg/endpoint"
	http1 "github.com/terasurfer/Cartelize-Server/accounts/pkg/http"
	service "github.com/terasurfer/Cartelize-Server/accounts/pkg/service"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CreateAdmin":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateAdmin", logger))},
		"CreateCustomer":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateCustomer", logger))},
		"GetAdminByEmail":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAdminByEmail", logger))},
		"GetAdminByID":       {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetAdminByID", logger))},
		"GetCustomerByEmail": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetCustomerByEmail", logger))},
		"GetCustomerByID":    {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetCustomerByID", logger))},
		"UpdateAdmin":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateAdmin", logger))},
		"UpdateCustomer":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateCustomer", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["CreateCustomer"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateCustomer")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateCustomer"))}
	mw["CreateAdmin"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateAdmin")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateAdmin"))}
	mw["GetCustomerByID"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetCustomerByID")), endpoint.InstrumentingMiddleware(duration.With("method", "GetCustomerByID"))}
	mw["GetCustomerByEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetCustomerByEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "GetCustomerByEmail"))}
	mw["GetAdminByID"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAdminByID")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAdminByID"))}
	mw["GetAdminByEmail"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetAdminByEmail")), endpoint.InstrumentingMiddleware(duration.With("method", "GetAdminByEmail"))}
	mw["UpdateCustomer"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateCustomer")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateCustomer"))}
	mw["UpdateAdmin"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateAdmin")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateAdmin"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"CreateCustomer", "CreateAdmin", "GetCustomerByID", "GetCustomerByEmail", "GetAdminByID", "GetAdminByEmail", "UpdateCustomer", "UpdateAdmin"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
